macbrew:
	gcc main.c -o main.out -I/opt/homebrew/include -I/opt/homebrew/include/freetype2 -L/opt/homebrew/lib -framework GLUT -framework OpenGL -lfreetype -w

linux:
	gcc main.c -o main.out -I/usr/include/freetype2 -lglut -lGL -lfreetype
