linux:
	clang main.c -o main.out -I/usr/include/freetype2 -lglfw -lGL -lfreetype

linuxbrew:
	g++ main.c -o main.out -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/include/freetype2 -L/home/linuxbrew/.linuxbrew/lib -lglfw3 -lGL -lfreetype
