windows-msys2:
	gcc main.c -o main -lglfw3 -lopengl32

macbrew:
	clang main.c -o main.out -I/opt/homebrew/include -L/opt/homebrew/lib -lglfw -framework OpenGL -w

linux:
	gcc main.c -o main.out -lglut -lGL -lm -w

dummy:

